pipeline:
  name: httptest
  identifier: httptest
  projectIdentifier: nytimes__devp_appdelivery_harness_test
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: account.nytimesOrgGhConnector
        repoName: httptest
        build: <+input>
        sparseCheckout: []
  stages:
    - stage:
        identifier: default
        name: default
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: gotest
                  name: gotest
                  spec:
                    connectorRef: account.harnessImage
                    image: golang:alpine
                    shell: Sh
                    command: go run gotest.tools/gotestsum@latest --junitfile report.xml
                    reports:
                      type: JUnit
                      spec:
                        paths:
                          - report.xml
                    envVariables:
                      CGO_ENABLED: "0"
                      GOOS: linux
                  timeout: ""
                  type: Run
              - step:
                  identifier: build
                  name: build
                  spec:
                    connectorRef: account.harnessImage
                    image: golang:alpine
                    shell: Sh
                    command: go build
                    envVariables:
                      CGO_ENABLED: "0"
                      GOOS: linux
                  timeout: ""
                  type: Run
                  when:
                    stageStatus: Success
              - step:
                  identifier: httptest
                  name: httptest
                  spec:
                    connectorRef: account.harnessImage
                    image: golang:alpine
                    shell: Sh
                    command: ./httptest
                    envVariables:
                      TEST_DIRECTORY: example-tests
                      TEST_ENV: dev
                      TEST_HOST: httpbin.org
                  timeout: ""
                  type: Run
                  when:
                    stageStatus: Success
              - step:
                  identifier: publish
                  name: publish
                  type: BuildAndPushDockerRegistry
                  spec:
                    connectorRef: account.harnessImage
                    repo: nytimes/httptest
                    tags:
                      - latest
                      # - ${DRONE_BRANCH}
                      # - ${DRONE_COMMIT}
                    buildArgs:
                      platform: linux/arm64,linux/amd64
                    envVariables:
                      PLUGIN_DRY_RUN: "true"
                  timeout: ""
                  when:
                    stageStatus: Success
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: account.kubernetesclusterconnector
              namespace: dv-cd
              automountServiceAccountToken: true
              nodeSelector: {}
              os: Linux
        type: CI
