kind: pipeline
name: default

workspace:
  base: /go
  path: src/github.com/nytimes/httptest

steps:
  - name: build
    image: golang:alpine
    commands:
      - pwd
      - go build
      - go test


# - name: docker
#   image: plugins/docker
#   settings:
#     repo: foo/bar
#     auto_tag: true
#     username: kevinbacon
#     password: pa55word
