---
kind: pipeline
name: testing
type: docker

workspace:
  base: /go
  path: src/github.com/nytimes/httptest

steps:
  - name: build
    image: golang:alpine
    environment:
      DOCKER_BUILDKIT: 1
      GOOS: linux
      CGO_ENABLED: 0
    commands:
      - go test ./...
      - go build

  - name: test
    image: golang:alpine
    environment:
      DOCKER_BUILDKIT: 1
      GOOS: linux
      CGO_ENABLED: 0
      TEST_DIRECTORY: example-tests
      TEST_HOST: httpbin.org
      TEST_ENV: dev
    commands:
      - ./httptest
---
kind: pipeline
name: publish-dev
type: docker

steps:
  - name: publish-dev-amd64
    image: plugins/docker
    environment:
      DOCKER_BUILDKIT: 1
    settings:
      platform: linux/amd64
      repo: nytimes/httptest
      build_args_from_env:
        - DRONE_BRANCH
        - DRONE_COMMIT
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      tags: [dev]
      auto_tag_suffix: amd64
      when:
        event: [push]
        branch:
          exclude: [main]

  - name: publish-dev-arm64
    image: plugins/docker
    environment:
      DOCKER_BUILDKIT: 1
    settings:
      platform: linux/arm64
      repo: nytimes/httptest
      build_args_from_env:
        - DRONE_BRANCH
        - DRONE_COMMIT
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      tags: [dev]
      auto_tag_suffix: arm64
      when:
        event: [push]
        branch:
          exclude: [main]

  - name: manifest-dev
    image: plugins/manifest
    environment:
      DOCKER_BUILDKIT: 1
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      target: nytimes/httptest:dev
      template: nytimes/httptest:dev-ARCH
      platforms:
        - linux/amd64
        - linux/arm64
    depends_on:
      - publish-dev-amd64
      - publish-dev-arm64

depends_on:
  - testing

---
kind: pipeline
name: publish
type: docker

steps:
  - name: publish-amd64
    image: plugins/docker
    environment:
      DOCKER_BUILDKIT: 1
    settings:
      platform: linux/amd64
      repo: nytimes/httptest
      build_args_from_env:
        - DRONE_BRANCH
        - DRONE_COMMIT
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      tags:
        - ${DRONE_TAG}
        - latest
      auto_tag_suffix: amd64
      when:
        event: [tag]
  - name: publish-arm64
    image: plugins/docker
    environment:
      DOCKER_BUILDKIT: 1
    settings:
      platform: linux/arm64
      repo: nytimes/httptest
      build_args_from_env:
        - DRONE_BRANCH
        - DRONE_COMMIT
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      tags:
        - ${DRONE_TAG}
        - latest
      auto_tag_suffix: arm64
      when:
        event: [tag]
#   - name: manifest-tagged
#     image: plugins/manifest
#     environment:
#       DOCKER_BUILDKIT: 1
#     settings:
#       username:
#         from_secret: docker_username
#       password:
#         from_secret: docker_password
#       target: nytimes/httptest:${DRONE_TAG}
#       template: nytimes/httptest:${DRONE_TAG}-ARCH
#       platforms:
#         - linux/amd64
#         - linux/arm64
#     # depends_on:
#     #   - publish-amd64
#     #   - publish-arm64

#   - name: manifest-latest
#     image: plugins/manifest
#     environment:
#       DOCKER_BUILDKIT: 1
#     settings:
#       username:
#         from_secret: docker_username
#       password:
#         from_secret: docker_password
#       target: nytimes/httptest:latest
#       template: nytimes/httptest:latest-ARCH
#       platforms:
#         - linux/amd64
#         - linux/arm64
#     # depends_on:
#     #   - publish-amd64
#     #   - publish-arm64
