---
kind: pipeline
name: default

workspace:
  base: /go
  path: src/github.com/nytimes/httptest

steps:
  - name: build
    image: golang:alpine
    environment:
      GOOS: linux
      CGO_ENABLED: 0
    commands:
      - go test
      - go build

  - name: test
    image: golang:alpine
    environment:
      GOOS: linux
      CGO_ENABLED: 0
      TEST_DIRECTORY: example-tests
      TEST_HOST: httpbin.org
      TEST_ENV: dev
    commands:
      - ./httptest

  - name: publish-dev
    image: plugins/docker
    settings:
      repo: nytimes/httptest
      build_args_from_env:
        - DRONE_BRANCH
        - DRONE_COMMIT
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      tags: [dev]
    when:
      event: [push]
      branch:
        exclude: [master]

  - name: publish
    image: plugins/docker
    settings:
      repo: nytimes/httptest
      build_args_from_env:
        - DRONE_BRANCH
        - DRONE_COMMIT
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      # Information on auto_tag: http://plugins.drone.io/drone-plugins/drone-docker/
      auto_tag: true
