kind: pipeline
name: default

workspace:
  base: /go
  path: src/github.com/nytimes/httptest

steps:
  - name: build
    image: golang:alpine
    environment:
      GOOS: linux
      CGO_ENABLED: 0
    commands:
      - go build
      - go test

  - name: publish
    image: plugins/docker
    repo: nytimes/httptest
    tags: [dev]
    secrets:
      - docker_username
      - docker_password
    when:
      event: [push]
